// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwAP87sp0CpXfg4uq6-nDbRatW-TAwOAo',
    appId: '1:144337075913:web:01824745ff69704b675718',
    messagingSenderId: '144337075913',
    projectId: 'chat-app-1298d',
    authDomain: 'chat-app-1298d.firebaseapp.com',
    storageBucket: 'chat-app-1298d.appspot.com',
    measurementId: 'G-90VC2Z92XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxp-s04XY1UpOIhoABXKJIobLpNBnrh0E',
    appId: '1:144337075913:android:ff6667ccea5800b4675718',
    messagingSenderId: '144337075913',
    projectId: 'chat-app-1298d',
    storageBucket: 'chat-app-1298d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJNUP7LGvsIxqmnSpKtPT_4Ps8-lYyyCU',
    appId: '1:144337075913:ios:c0baaf4462c870db675718',
    messagingSenderId: '144337075913',
    projectId: 'chat-app-1298d',
    storageBucket: 'chat-app-1298d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJNUP7LGvsIxqmnSpKtPT_4Ps8-lYyyCU',
    appId: '1:144337075913:ios:ac2fa534edc69c63675718',
    messagingSenderId: '144337075913',
    projectId: 'chat-app-1298d',
    storageBucket: 'chat-app-1298d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
